#!/bin/bash
ip=$2
nume=$1
dns=$3

#executam nslookup, pastram doar liniile care au in nume Address
#-v face operatia inversa, pastreaza liniile care NU au #
# awk print $2 pastreaza al doilea argument Address: 192.168.0.255 ia doar 192....

ip_real=$(nslookup $nume $dns | grep "Address" | grep -v "#" | awk '{print $2}'| head -n 1)
echo $ip_real
echo "\n"
#folosim DNS ul de la google ca sa nu luam mereu valorile gresite din /etc/hosts
#DNS ul afiseaza si adresa ipv6 asa ca luam doar prima linie, adresa ipv4

#verificare daca ip_real e diferit de zero si daca este egal cu ip ul din /etc/hosts
if [[ -n "$ip_real" ]] && [[ "$ip" != "$ip_real" ]]; then
    echo "Bogus IP for $nume "
else 
	echo "Ip-ul este bun"

fi
